kind: Service
apiVersion: v1
metadata:
  name: redis-tinyurl-service
  labels:
    app: redis-tinyurl
spec:
  selector:
    app: redis-tinyurl
  type: LoadBalancer
  ports:
    - port: 6666
      targetPort: 6666
      protocol: TCP